version: "3.9"

services:
  facturacion:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - "nonexistent:latest"
    ports:
      - 8281:8281
    restart: always
    environment:
      - CUIT=30518594466
      - CERT=um.crt
      - PRIVATEKEY=um.key
      - PRODUCTION=TRUE
